# Generated by Django 3.2.3 on 2021-06-13 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Admin1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='addProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=255)),
                ('p_desc', models.TextField()),
                ('p_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bid_ends', models.DateField(null=True)),
                ('Main_image', models.ImageField(upload_to='mainimage/')),
                ('secondary_image', models.ImageField(upload_to='secimage/')),
                ('ter_image', models.ImageField(upload_to='terimage/')),
                ('Status', models.CharField(default='some string', max_length=50)),
                ('Seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.person')),
                ('p_cate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin1.add_category')),
            ],
        ),
    ]
