# Generated by Django 3.2.3 on 2021-06-14 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bidding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bid_Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.addproduct')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.person')),
            ],
        ),
    ]
