# Generated by Django 3.1.7 on 2021-06-17 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_auto_20210615_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_name', models.CharField(max_length=255)),
                ('pinCode', models.PositiveIntegerField()),
                ('state', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('HouseName', models.CharField(max_length=150)),
                ('landMark', models.CharField(max_length=150)),
                ('user_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.person')),
            ],
        ),
    ]
