# Generated by Django 3.1.7 on 2021-06-20 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Status',
            field=models.CharField(default='status', max_length=50),
            preserve_default=False,
        ),
    ]
